from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def test_no_colab_artifacts_remain() -> None:
    forbidden = (
        "google." + "colab",
        "!" + "pip",
        "# " + "CELL",
        "Automatically generated by " + "Colab",
    )
    scanned = []
    for path in ROOT.rglob("*.py"):
        if any(part.startswith(".") for part in path.relative_to(ROOT).parts):
            continue
        text = path.read_text(encoding="utf-8")
        scanned.append(path)
        assert not any(marker in text for marker in forbidden), path
    assert scanned


def test_gitignore_blocks_generated_artifacts() -> None:
    gitignore = (ROOT / ".gitignore").read_text(encoding="utf-8")
    required_patterns = ("packet_*.pdf", "map_exhibit.png", ".cache/", "__pycache__/")
    for pattern in required_patterns:
        assert pattern in gitignore


def test_readme_contains_venue_ladder_and_disclaimers() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    required_text = (
        "NOT LEGAL ADVICE",
        "Cook County Assessor",
        "Board of Review",
        "Illinois Property Tax Appeal Board",
        "PTAB filing is due within 30 days",
        "SOCRATA_APP_TOKEN",
    )
    for text in required_text:
        assert text in readme
